### ISSUE TITLE
Received error: certificate has expired (CERT_HAS_EXPIRED)

### ISSUE THREAD

**Issue by alexweininger** [chrmarti/vscode-network-proxy-test#4]
Hi, in the Azure Account extension we have some customers who get errors related to network requests. When running the network proxy test they get a "Received error: certificate has expired (CERT_HAS_EXPIRED)" error.

What is the recommended steps to solve this?

https://github.com/microsoft/vscode-azure-account/issues/836#issuecomment-1749144957

**Comment by chrmarti** [comment]
Continued there.
